services:
  - type: web
    name: shawon-burger-shop
    env: node
    region: singapore
    buildCommand: |
      chmod +x start.sh
      npm install
    startCommand: ./start.sh
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    autoDeploy: true
